import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Footer from '@/app/footer/footer'; 
import ContactUs from '@/app/contact/contact';
import ProjectPage from '@/app/projects/project'
import Header from '@/app/header/header'
import TextImageLayout from "@/app/Lorem/TextImageLayout";
import ImageLayout from "./imagelayout/ImageLayout";
import About from "./about/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Header />
        <br></br>
        <br></br>
        <TextImageLayout/>
        <About/>
        <ImageLayout/>
        {children}
        {/* Correct Footer component syntax */}
        <ProjectPage/>
        <ContactUs/>
        <Footer />
      </body>
    </html>
  );
}
